import type { Job } from "../types/job.types";
import { JobStatus, JobType } from "../types/job.types";

export const mockJobs: Job[] = [
	{
		id: "job-001",
		title: "Senior Medical Officer - Emergency Department",
		description:
			"We are seeking an experienced Senior Medical Officer to join our Emergency Department. The ideal candidate will have strong clinical skills, excellent communication abilities, and the capacity to work effectively in a fast-paced environment. You will be responsible for managing acute medical cases, supervising junior staff, and ensuring high-quality patient care.",
		location: "Kuala Lumpur General Hospital",
		jobType: JobType.FULL_TIME,
		status: JobStatus.PUBLISHED,
		salary: {
			min: 12000,
			max: 18000,
			currency: "MYR",
		},
		requirements: [
			"MBBS or equivalent medical degree",
			"Valid MMC registration",
			"Minimum 3 years post-graduate experience",
			"ACLS and ATLS certification",
			"Strong decision-making skills under pressure",
		],
		benefits: [
			"Medical insurance coverage",
			"Annual leave 21 days",
			"Professional development allowance",
			"On-call allowance",
			"Parking provided",
		],
		startDate: "2025-11-01T00:00:00.000Z",
		contactEmail: "hr@klgh.gov.my",
		contactPhone: "+60123456789",
		createdAt: "2025-10-15T08:30:00.000Z",
		updatedAt: "2025-10-20T14:22:00.000Z",
	},
	{
		id: "job-002",
		title: "Locum General Practitioner - Weekend Coverage",
		description:
			"Private clinic in Petaling Jaya seeking a locum GP for weekend coverage. Handle general consultations, minor procedures, and health screenings. Flexible schedule with competitive hourly rates.",
		location: "Petaling Jaya, Selangor",
		jobType: JobType.LOCUM,
		status: JobStatus.PUBLISHED,
		salary: {
			min: 150,
			max: 200,
			currency: "MYR",
		},
		requirements: [
			"MBBS with valid MMC registration",
			"Minimum 2 years clinical experience",
			"Good communication skills in English and Bahasa Malaysia",
			"Comfortable with EMR systems",
		],
		benefits: [
			"Flexible working hours",
			"Competitive hourly rate",
			"Friendly work environment",
		],
		startDate: "2025-11-05T00:00:00.000Z",
		endDate: "2026-01-31T00:00:00.000Z",
		contactEmail: "admin@pjclinic.com.my",
		contactPhone: "+60198765432",
		createdAt: "2025-10-18T10:15:00.000Z",
		updatedAt: "2025-10-18T10:15:00.000Z",
	},
	{
		id: "job-003",
		title: "Consultant Paediatrician",
		description:
			"Leading private hospital in Penang is looking for a Consultant Paediatrician to join our growing team. You will provide comprehensive paediatric care, manage inpatient and outpatient services, and contribute to teaching programs.",
		location: "Penang Island",
		jobType: JobType.FULL_TIME,
		status: JobStatus.PUBLISHED,
		salary: {
			min: 20000,
			max: 30000,
			currency: "MYR",
		},
		requirements: [
			"MBBS with MMC registration",
			"Master's degree in Paediatrics or equivalent",
			"Minimum 5 years experience as a paediatrician",
			"NSR certification preferred",
			"Excellent interpersonal skills",
		],
		benefits: [
			"Comprehensive medical coverage for family",
			"Annual performance bonus",
			"CME allowance",
			"Relocation assistance",
			"Annual leave 28 days",
		],
		startDate: "2025-12-01T00:00:00.000Z",
		contactEmail: "recruitment@penangmedical.com",
		contactPhone: "+60164445555",
		createdAt: "2025-10-10T09:00:00.000Z",
		updatedAt: "2025-10-22T16:45:00.000Z",
	},
	{
		id: "job-004",
		title: "Part-Time Medical Officer - Occupational Health",
		description:
			"Manufacturing company seeking a part-time Medical Officer for occupational health services. Conduct pre-employment medicals, health surveillance, and workplace health programs.",
		location: "Shah Alam, Selangor",
		jobType: JobType.PART_TIME,
		status: JobStatus.PUBLISHED,
		salary: {
			min: 5000,
			max: 7000,
			currency: "MYR",
		},
		requirements: [
			"MBBS with valid MMC registration",
			"Certificate in Occupational Health (preferred)",
			"Knowledge of OSH regulations",
			"Available 2-3 days per week",
		],
		startDate: "2025-12-01T00:00:00.000Z",
		benefits: [
			"Flexible schedule",
			"Professional development opportunities",
			"Transport allowance",
		],
		contactEmail: "hr@manufacturing.com.my",
		contactPhone: "+60123334444",
		createdAt: "2025-10-12T11:20:00.000Z",
		updatedAt: "2025-10-12T11:20:00.000Z",
	},
	{
		id: "job-005",
		title: "Contract Medical Officer - COVID-19 Assessment Centre",
		description:
			"6-month contract position for Medical Officer at COVID-19 Assessment Centre. Responsibilities include patient assessment, swab procedures, and health education.",
		location: "Johor Bahru",
		jobType: JobType.CONTRACT,
		status: JobStatus.DRAFT,
		salary: {
			min: 8000,
			max: 10000,
			currency: "MYR",
		},
		requirements: [
			"MBBS with MMC registration",
			"Willing to work shifts including weekends",
			"Good knowledge of infectious disease protocols",
		],
		contactPhone: "+60123456789",
		benefits: [
			"Contract completion bonus",
			"Medical coverage",
			"Meal allowance",
		],
		startDate: "2025-09-01T00:00:00.000Z",
		endDate: "2026-02-28T00:00:00.000Z",
		contactEmail: "covid@jbhealth.gov.my",
		createdAt: "2025-08-15T08:00:00.000Z",
		updatedAt: "2025-10-01T10:30:00.000Z",
	},
	{
		id: "job-006",
		title: "Locum Anaesthetist - Private Hospital",
		description:
			"Experienced anaesthetist needed for locum coverage during staff leave. Handle various surgical cases including general, orthopaedic, and obstetric procedures.",
		location: "Ipoh, Perak",
		jobType: JobType.LOCUM,
		status: JobStatus.PUBLISHED,
		salary: {
			min: 300,
			max: 400,
			currency: "MYR",
		},
		requirements: [
			"MBBS with MMC registration",
			"Master's in Anaesthesiology",
			"Minimum 3 years experience",
			"Current ACLS certification",
		],
		benefits: [
			"Competitive daily rate",
			"Accommodation provided",
			"Meals included",
		],
		startDate: "2025-11-15T00:00:00.000Z",
		endDate: "2025-12-15T00:00:00.000Z",
		contactEmail: "anaesthesia@ipohhospital.com",
		contactPhone: "+60175556666",
		createdAt: "2025-10-20T13:00:00.000Z",
		updatedAt: "2025-10-20T13:00:00.000Z",
	},
	{
		id: "job-007",
		title: "Medical Officer - General Practice (New Graduate)",
		description:
			"Excellent opportunity for new medical graduates to gain experience in a busy general practice setting. Comprehensive training and mentorship provided.",
		location: "Kota Kinabalu, Sabah",
		jobType: JobType.FULL_TIME,
		status: JobStatus.PUBLISHED,
		salary: {
			min: 6000,
			max: 8000,
			currency: "MYR",
		},
		requirements: [
			"MBBS with provisional/full MMC registration",
			"Fresh graduates encouraged to apply",
			"Passionate about primary care",
			"Good communication skills",
		],
		benefits: [
			"Structured training program",
			"Medical insurance",
			"Annual leave 14 days",
			"Career progression opportunities",
		],
		startDate: "2025-11-20T00:00:00.000Z",
		contactEmail: "careers@kkmedical.com",
		contactPhone: "+60188889999",
		createdAt: "2025-10-19T09:30:00.000Z",
		updatedAt: "2025-10-19T09:30:00.000Z",
	},
	{
		id: "job-008",
		title: "Specialist in Internal Medicine",
		description:
			"Established private hospital seeking a Specialist in Internal Medicine. Manage complex medical cases, provide consultations, and participate in teaching activities.",
		location: "Kuching, Sarawak",
		jobType: JobType.FULL_TIME,
		status: JobStatus.DRAFT,
		salary: {
			min: 25000,
			max: 35000,
			currency: "MYR",
		},
		contactPhone: "+60123456789",
		startDate: "2025-11-25T00:00:00.000Z",
		requirements: [
			"MBBS with MMC registration",
			"Master's in Internal Medicine or equivalent",
			"NSR certification",
			"Minimum 7 years post-graduate experience",
		],
		benefits: [
			"Attractive remuneration package",
			"Family medical coverage",
			"Annual bonus",
			"CME support",
			"Relocation package",
		],
		contactEmail: "specialist@kuchinghealth.com",
		createdAt: "2025-10-23T15:00:00.000Z",
		updatedAt: "2025-10-24T10:00:00.000Z",
	},
	{
		id: "job-009",
		title: "Part-Time GP - Evening Clinic",
		description:
			"Panel clinic in Subang Jaya looking for a part-time GP for evening sessions (6pm-10pm). Handle general consultations and minor ailments.",
		location: "Subang Jaya, Selangor",
		jobType: JobType.PART_TIME,
		status: JobStatus.PUBLISHED,
		salary: {
			min: 100,
			max: 120,
			currency: "MYR",
		},
		startDate: "2025-11-26T00:00:00.000Z",
		requirements: [
			"MBBS with MMC registration",
			"Minimum 1 year experience",
			"Available weekday evenings",
		],
		benefits: ["Flexible hours", "Supportive team", "Regular patient base"],
		contactEmail: "evening@subangclinic.com",
		contactPhone: "+60122223333",
		createdAt: "2025-10-21T12:00:00.000Z",
		updatedAt: "2025-10-21T12:00:00.000Z",
	},
	{
		id: "job-010",
		title: "Contract Psychiatrist - Mental Health Program",
		description:
			"12-month contract for a Psychiatrist to lead mental health initiatives in a corporate wellness program. Provide consultations, develop programs, and conduct workshops.",
		location: "Cyberjaya, Selangor",
		jobType: JobType.CONTRACT,
		status: JobStatus.PUBLISHED,
		salary: {
			min: 15000,
			max: 20000,
			currency: "MYR",
		},
		requirements: [
			"MBBS with MMC registration",
			"Master's in Psychiatry",
			"Experience in corporate mental health preferred",
			"Strong presentation skills",
		],
		benefits: [
			"Innovative work environment",
			"Professional development budget",
			"Flexible working arrangements",
			"Medical coverage",
		],
		startDate: "2025-12-01T00:00:00.000Z",
		endDate: "2026-11-30T00:00:00.000Z",
		contactEmail: "wellness@techcorp.com.my",
		contactPhone: "+60197778888",
		createdAt: "2025-10-17T14:30:00.000Z",
		updatedAt: "2025-10-22T11:15:00.000Z",
	},
	{
		id: "job-011",
		contactPhone: "+60123456789",
		title: "Locum Medical Officer - Rural Health Clinic",
		description:
			"Locum coverage needed for rural health clinic. Provide primary care services to underserved communities. Accommodation and transport provided.",
		location: "Kuala Terengganu, Terengganu",
		jobType: JobType.LOCUM,
		status: JobStatus.CLOSED,
		salary: {
			min: 180,
			max: 220,
			currency: "MYR",
		},
		requirements: [
			"MBBS with MMC registration",
			"Willing to work in rural setting",
			"Basic emergency care skills",
		],
		benefits: [
			"Accommodation provided",
			"Transport allowance",
			"Meaningful work experience",
		],
		startDate: "2025-10-01T00:00:00.000Z",
		endDate: "2025-10-31T00:00:00.000Z",
		contactEmail: "rural@terengganuhealth.gov.my",
		createdAt: "2025-09-10T08:00:00.000Z",
		updatedAt: "2025-10-15T09:00:00.000Z",
	},
	{
		id: "job-012",
		title: "Orthopaedic Surgeon - Sports Medicine Focus",
		description:
			"Sports medicine centre seeking an Orthopaedic Surgeon with interest in sports injuries. Manage athletic injuries, perform arthroscopic procedures, and work with professional athletes.",
		location: "Bukit Jalil, Kuala Lumpur",
		jobType: JobType.FULL_TIME,
		status: JobStatus.PUBLISHED,
		salary: {
			min: 30000,
			max: 45000,
			currency: "MYR",
		},
		requirements: [
			"MBBS with MMC registration",
			"Master's in Orthopaedic Surgery",
			"Fellowship in Sports Medicine (preferred)",
			"Arthroscopy experience essential",
			"NSR certification",
		],
		benefits: [
			"Work with elite athletes",
			"State-of-the-art facilities",
			"International conference opportunities",
			"Performance bonus",
			"Medical coverage",
		],
		startDate: "2026-01-01T00:00:00.000Z",
		contactEmail: "sports@bukitjalilmed.com",
		contactPhone: "+60123456700",
		createdAt: "2025-10-22T10:00:00.000Z",
		updatedAt: "2025-10-24T15:30:00.000Z",
	},
];
